from abc import ABC, abstractmethod
from decimal import Decimal
from app.models.domain import OrderRequest, Position, Quote
class Broker(ABC):
    @abstractmethod
    async def buying_power(self) -> Decimal: ...
    @abstractmethod
    async def positions(self) -> list[Position]: ...
    @abstractmethod
    async def quote(self, symbol: str) -> Quote: ...
    @abstractmethod
    async def submit(self, order: OrderRequest) -> str: ...
    @abstractmethod
    async def cancel(self, order_id: str) -> None: ...
